language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - cp memberarea/configuration.example.py memberarea/configuration.py
script:
  - python manage.py test
