# Generated by Django 2.1a1 on 2018-05-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(default=2018)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('missingHoursPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fromYearOfBirth', models.IntegerField(blank=True, null=True)),
                ('toYearOfBirth', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-year', '-fromYearOfBirth', '-toYearOfBirth'),
            },
        ),
        migrations.CreateModel(
            name='WorkedHoursStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('hoursConfirmed', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hoursNotConfirmed', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', '-year'),
            },
        ),
        migrations.CreateModel(
            name='Workitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('duration_expected', models.IntegerField()),
                ('due_at', models.DateField(db_index=True)),
                ('max_assignees', models.IntegerField()),
            ],
            options={
                'ordering': ('-due_at',),
                'permissions': (('assign_workitem', 'Can assign a workitem to an user'), ('tag_workitem', 'Can assign a tag to a workitem')),
            },
        ),
        migrations.CreateModel(
            name='WorkitemAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_real', models.IntegerField(blank=True, null=True)),
                ('done', models.BooleanField(db_index=True, default=False)),
                ('done_at', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_workitems', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_workitems', to=settings.AUTH_USER_MODEL)),
                ('workitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workitems.Workitem')),
            ],
            options={
                'permissions': (('verify_workitemassignment', 'Can verify a workitem assignment'), ('markdone_workitemassignment', 'Can mark a workitem assignment as done')),
            },
        ),
        migrations.AddField(
            model_name='workitem',
            name='assigned_to',
            field=models.ManyToManyField(through='workitems.WorkitemAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
