# Generated by Django 2.1a1 on 2018-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
